controller_manager:
  ros__parameters:
    update_rate: 100

ur10e_arm_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - ur10e_shoulder_pan_joint
      - ur10e_shoulder_lift_joint
      - ur10e_elbow_joint
      - ur10e_wrist_1_joint
      - ur10e_wrist_2_joint
      - ur10e_wrist_3_joint
    state_publish_rate: 50
    action_monitor_rate: 20
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      trajectory:
        goal_time: 0.1
        stopped_velocity_tolerance: 0.01

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
