controller_list:
  - name: fake_ur_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ur10e_shoulder_pan_joint
      - ur10e_shoulder_lift_joint
      - ur10e_elbow_joint
      - ur10e_wrist_1_joint
      - ur10e_wrist_2_joint
      - ur10e_wrist_3_joint
  - name: fake_ur_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: ur_arm
    pose: home